FROM node:22-alpine AS build

ARG VITE_API_URL
ARG VITE_SSE_URL
ARG VITE_ACK_URL
ARG VITE_API_BASE_URL
ARG VITE_APP_GOOGLE_MAPS_API_KEY
ARG VITE_GOOGLE_PICKER_API_KEY
ARG VITE_GOOGLE_PICKER_CLIENT_ID
ARG VITE_GOOGLE_PICKER_SCOPE
ARG VITE_GOOGLE_PICKER_APP_ID

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SSE_URL=$VITE_SSE_URL
ENV VITE_ACK_URL=$VITE_ACK_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_APP_GOOGLE_MAPS_API_KEY=$VITE_APP_GOOGLE_MAPS_API_KEY
ENV VITE_GOOGLE_PICKER_API_KEY=$VITE_GOOGLE_PICKER_API_KEY
ENV VITE_GOOGLE_PICKER_CLIENT_ID=$VITE_GOOGLE_PICKER_CLIENT_ID
ENV VITE_GOOGLE_PICKER_SCOPE=$VITE_GOOGLE_PICKER_SCOPE
ENV VITE_GOOGLE_PICKER_APP_ID=$VITE_GOOGLE_PICKER_APP_ID

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
